//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowDetroit.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public string SiteName { get; set; }
        public string Recommended { get; set; }
        public string Review1 { get; set; }
        public string UserID { get; set; }
        public int ReviewNumber { get; set; }
        public int Rating { get; set; }
        public string imageURL { get; set; }
    

        public virtual AspNetUser AspNetUser { get; set; }
        [JsonIgnore]
        public virtual Landmark Landmark { get; set; }
    }
}
